#!/usr/bin/env python3
"""Q4c generator: gp associativity on symbolic polynomials, decided by {==}.
usage: gen_q04c.py SIG OUT.bend   (SIG like ZPPP)"""
import sys, os
SIG, OUT = sys.argv[1], sys.argv[2]
N = len(SIG); M = 1 << N
QN = {"Z": "QZ{}", "P": "QP{}", "N": "QN{}"}
here = os.path.dirname(os.path.abspath(sys.argv[0]))
src = open(os.path.join(here, "q03_mv_tree.bend")).read()
src = src[:src.index("def main()")]
src = src.replace("import Base", "import Base\nimport ./q04b_poly.bend as P", 1)
src = src.replace("# Q3:", f"# Q4c (generated by gen_q04c.py {SIG}): gp associativity over P.Poly by {{==}}.\n# Layer S copied from q03:\n# Q3:", 1)
def tree(d, xs):
    if d == N: return f"S1{{P.Poly.var({xs[0]}n)}}"
    h = len(xs) // 2
    return f"N{{{tree(d+1, xs[:h])}, {tree(d+1, xs[h:])}}}"
T = "MV(P.Poly(), Sig())"
G = "MV.gp(~P.Poly(), ~P.Poly.add, ~P.Poly.mul, ~P.Poly.neg, Sig(), False{}, False{}, "
src += f"""def Sig() -> List<&2, Q>:
  [{", ".join(QN[c] for c in SIG)}]

def A() -> {T}:
  {tree(0, list(range(M)))}

def B() -> {T}:
  {tree(0, list(range(M, 2*M)))}

def C() -> {T}:
  {tree(0, list(range(2*M, 3*M)))}

law assoc:
  {{{G}{G}A(), B()), C()) == {G}A(), {G}B(), C())) : {T}}}

def assoc():
  {{==}}
"""
open(OUT, "w").write(src)
