#!/usr/bin/env python3
"""Q4 generator: a flat 2^n-coefficient geometric-product kernel that mirrors
the Layer-S tree spec (spikes/q03_mv_tree.bend MV.gp) term for term, plus the
law kernel == spec over an opaque ring, proven by {==}.

usage: gen_q04.py SIG OUT.bend      SIG like ZPPP (Z=0, P=+1, N=-1), e0 first
"""
import sys

SIG = sys.argv[1]
OUT = sys.argv[2]
N = len(SIG)
QN = {"Z": "QZ{}", "P": "QP{}", "N": "QN{}"}


# --- symbolic mirror of MV.add / MV.gp -------------------------------------
# a tree is ("S1", expr) | ("S0",) | ("N", e, r) | ("Z",)

def add(depth, a, b):
    if depth == N:
        if a[0] == "S0":
            return b
        if b[0] == "S0":
            return a
        return ("S1", f"add({a[1]}, {b[1]})")
    if a[0] == "Z":
        return b
    if b[0] == "Z":
        return a
    return ("N", add(depth + 1, a[1], b[1]), add(depth + 1, a[2], b[2]))


def gp(depth, f, n, x, y):
    if depth == N:
        if x[0] == "S0" or y[0] == "S0":
            return ("S0",)
        m = f"mul({x[1]}, {y[1]})"
        return ("S1", f"neg({m})" if n else m)
    if x[0] == "Z" or y[0] == "Z":
        return ("Z",)
    q = SIG[depth]
    _, x1, x2 = x
    _, y1, y2 = y
    nf = n ^ f
    d = depth + 1
    e = add(d, gp(d, f, nf, x1, y2), gp(d, not f, n, x2, y1))
    r2 = gp(d, f, n, x2, y2)
    if q == "Z":
        return ("N", e, r2)
    if q == "P":
        return ("N", e, add(d, gp(d, not f, nf, x1, y1), r2))
    return ("N", e, add(d, gp(d, not f, not nf, x1, y1), r2))


def tree(depth, names):
    if depth == N:
        return ("S1", names[0])
    h = len(names) // 2
    return ("N", tree(depth + 1, names[:h]), tree(depth + 1, names[h:]))


def dense(t):
    if t[0] == "S1":
        return [t[1]]
    return dense(t[1]) + dense(t[2])


def bend_tree(depth, names):
    if depth == N:
        return f"S1{{{names[0]}}}"
    h = len(names) // 2
    return f"N{{{bend_tree(depth + 1, names[:h])}, {bend_tree(depth + 1, names[h:])}}}"


M = 1 << N
A = [f"a{i}" for i in range(M)]
B = [f"b{i}" for i in range(M)]
out = dense(gp(0, False, False, tree(0, A), tree(0, B)))
nmul = sum(o.count("mul(") for o in out)

sig_list = "[" + ", ".join(QN[c] for c in SIG) + "]"
fields = ", ".join(f"c{i}: T" for i in range(M))
src = open(sys.argv[0].replace("gen_q04.py", "q03_mv_tree.bend")).read()
src = src[:src.index("def main()")]
src = src.replace("# Q3:", "# Q4 (generated by gen_q04.py " + SIG + "), Layer S copied from q03:\n# Q3:", 1)

ops = "~T: Data, ~add: T -> T -> T, ~mul: T -> T -> T, ~neg: T -> T"
tops = "~T, ~add, ~mul, ~neg"
pa = ", ".join("+" + a for a in A)
pb = ", ".join("+" + b for b in B)
src += f"""
def Sig() -> List<&2, Q>:
  {sig_list}

type Flat<-T: Data> is Data:
  Flat{{{fields}}}

def Flat.tree(-T: Data, x: Flat<T>) -> MV(T, Sig()):
  match x:
    case Flat{{{", ".join(A)}}}:
      {bend_tree(0, A)}

# the mirror kernel: {nmul} multiplies
def Flat.gp({ops}, x: Flat<T>, y: Flat<T>) -> Flat<T>:
  match x y:
    case Flat{{{pa}}} Flat{{{pb}}}:
      Flat{{{", ".join(out)}}}

law gp_mirror:
  for ~T: Data
  for ~add: T -> T -> T
  for ~mul: T -> T -> T
  for ~neg: T -> T
  for x: Flat<T>
  for y: Flat<T>
  {{Flat.tree(T, Flat.gp({tops}, x, y)) == MV.gp({tops}, Sig(), False{{}}, False{{}}, Flat.tree(T, x), Flat.tree(T, y)) : MV(T, Sig())}}

def gp_mirror(T, add, mul, neg, x, y):
  match x y:
    case Flat{{{", ".join(A)}}} Flat{{{", ".join(B)}}}:
      {{==}}
"""
open(OUT, "w").write(src)
print(f"{OUT}: {M} coefficients, {nmul} multiplies, {sum(len(o) for o in out)} chars of kernel")
